dist: trusty
sudo: false

language: node_js
node_js:
  - "6"

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  - export CHROME_BIN=chromium-browser
  - xvfb-run -a npm run build
  